### PR TITLE
DM-13163: Refactor ap_pipe to use CmdLineTask primitives

### PR DESCRIPTION
**Pull request by kfindeisen**
This PR registers dataset mappings for configs and metadata persisted by `ApPipeTask`.

### CODE REVIEW

**Review by r-owen — COMMENTED** [review]
Why is this needed? It seems to match the entries in obs_base (other than indentation). I would have thought it could be omitted.

**Comment by kfindeisen** [comment]
I was using `processCcd_config` and `processCcd_metadata` as templates; since they use full definitions, I assumed that for some reason they can't see what's in `obs_base`.

**Comment by kfindeisen** [comment]
(Note that due to pipeline limitations, `obs_decam` is the only one I'm in any position to test at the moment.)

**Comment by r-owen** [comment]
If obs_x can't see the defaults in obs_base then something is seriously wrong. I suggest not making these changes until you have strong evidence they are needed. You could put them on a private branch if you want to save them.

**Comment by kfindeisen** [comment]
No, they're pretty easy to reproduce. Should the obs packages that still use PAF instead of YAML files also be able to see the `obs_base` defaults?

**Comment by r-owen** [comment]
I believe obs packages that use .paf files do still use the configuration in obs_base, but I suggest asking on the DM room for details. In particular I don't know if it is allowed to just specify fields you wish to override in the .paf file.

**Review by r-owen — APPROVED** [review]

**Pull request merged**
